### ISSUE TITLE
Update wiki related to `docx`

### ISSUE THREAD

**Issue by avahoffman** [jhudsl/OTTR_Template#312]
see discussion here: #306

**Comment by cansavvy** [comment]
Done: https://github.com/jhudsl/DaSL_Course_Template_Bookdown/wiki/Using-Google-Docs-to-solicit-feedback

**Comment by avahoffman** [comment]
@cansavvy Can I add some info about the yaml? something like what we put in the gdscn activity?
```
output:
    bookdown::word_document2:
      reference_docx: assets/gdscn-template.docx
      toc: true
```
