### ISSUE TITLE
Have one core GitHub actions set of files that are called by users's github actions 

### ISSUE THREAD

**Issue by cansavvy** [jhudsl/OTTR_Template#502]
Duh, this was in front of my all along and I didn't think of it. 

We could reference a main copy of the OTTR github actions that are here and not require people to make copies! This would make it so people can more easily customize files like "pull-request.yml" and wouldn't have to depend on the sync PRs to update the GHA. 

Instead `pull-request.yml` would just have a series of things like this: 
````
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - uses: jhudsl/OTTR_Template/.github/workflows/style-code.yml 
```
