### ISSUE TITLE
["Problem"] When to authenticate inside workflows??

### ISSUE THREAD

**Issue by avahoffman** [jhudsl/OTTR_Template#551]
It's unclear when we need to refer to the token in this repo's workflows. 

Example:

The following works fine with all jhudsl repos (AFAIK):

https://github.com/jhudsl/OTTR_Template/blob/ca0aa220cbc0b4dc9e221dbe571de85d6af2795b/.github/workflows/pull_request.yml#L11-L19

However, a [fhdsl repo](https://github.com/fhdsl/DaSL_Collection) required ([permalink](https://github.com/fhdsl/DaSL_Collection/blob/a45b8fe37a4b61b6f04f5f6e15cba52b2623d03e/.github/workflows/pull_request.yml#L11-L20)):  
``` 
yaml-check:
    name: Load user automation choices
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}
```

Why the different authentication needs? It would be great if this could be consistent and we have some sort of convention around it. For example, specifying the GH_PAT at the start of each workflow so they aren't scattered around different jobs.
