### ISSUE TITLE
`test-send-updates.yml` tests on all groups

### ISSUE THREAD

**Issue by avahoffman** [jhudsl/OTTR_Template#558]
if I have two groups on the sync.yml eg
```
group:
  # first group
  - files:
      - source: workflows/build.yml
        dest: .github/workflows/build.yml
      - source: LICENSE.md
        dest: LICENSE
    repos: |
      user/repo1
      user/repo2

  # second group
  - files: 
      - source: configs/dependabot.yml
        dest: .github/dependabot.yml
    repos: |
      user/repo3
      user/repo4
```

`test-send-updates.yml` will test everything, not just the appropriate group.

I was pretty confused why this was happening until I dug into the `switch-sync-repo.R` file, so might be worth adding some FYI or building out this capability a bit more.
