### ISSUE TITLE
Possible bug / security issue with checkout action

### ISSUE THREAD

**Issue by avahoffman** [jhudsl/OTTR_Template#561]
@cansavvy wanted to make sure you saw this.

We were having some render-all workflows failing at git checkout: 
https://github.com/jhudsl/GDSCN_Book_Statistics_for_Genomics_scRNA-seq/runs/8164703061?check_suite_focus=true
https://github.com/jhudsl/GDSCN_Book_Statistics_for_Genomics_scRNA-seq/pull/11

```
Run git config --local user.email "itcrtrainingnetwork@gmail.com"
fatal: --local can only be used inside a git repository
Error: Process completed with exit code 128.
```

This looks similar to the issue [here](https://github.com/peter-evans/create-pull-request/issues/1170).

We solved it with the following ([example here](https://github.com/jhudsl/GDSCN_Book_Statistics_for_Genomics_scRNA-seq/pull/13/commits/de4a55cff50a305bbc347ee23d1a0a627adaf778)):
```
    steps:
      - name: Checkout files
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Set up git checkout
      - name: Set up git checkout
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config --local user.email "itcrtrainingnetwork@gmail.com"
          git config --local user.name "jhudsl-robot"
```

Not sure if we want to implement this just yet, since the checkout actions team might have a fix for it. Suggest keeping a close eye on it!
